[package]
name = "guryvsr"
version = "1.0.0"
description = "Rust implementation of the esoteric programming language gur yvsr"
license = "Apache-2.0"
edition = "2024"
readme = "README.md"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
regex = "1.11.2"
